# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894050fa2102f2092680f93f1ef9bff703d9cc6a8959525d8ca913284610070e7f8ee0b2c140914bf95125c4755738f59f4fcde01fbf1b4340462bb0aff21f1e

test:
  secret_key_base: 2e89581f4388bdda69fe9b55e2b5c490f29ce1afabf485ae9e6c1e96539bb3118369fc4796c5c980dbe31d1dd5c0e1fee9716046839d2ece7c750cd3bf67f0e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
